### ISSUE TITLE
NodeJS version should be configurable

### ISSUE THREAD

**Issue by AnnaDodson** [dvsa/.github#21]
NodeJS version can be passed into the install dependencies workflow but currently isn't getting passed in through from the other workflows.

Example, the build workflow should accept a NodeJS version arg that is then passed into the install dependencies workflow so the NodeJS version needed is being used for `npm i` and `npm build`

**Comment by sdh100shaun** [comment]
is this fixed by [bbe714c](https://github.com/dvsa/.github/commit/bbe714cccb2e04436c41f78d46a2861469ad39bf) @AnnaDodson

**Comment by AnnaDodson** [comment]
Yes this was done!
Closed in #22
