### ISSUE TITLE
Node 16 Actions require updating to Node 20

### ISSUE THREAD

**Issue by jakedanielturner** [dvsa/.github#54]
Various Actions used throughout Node workflows in this repository are using Node 16. These Actions will be deprecated in November, in accordance with the EOL of Node 16 (see more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/).

All Actions affected have newer versions which use Node 20. Update these Actions to their latest versions where possible.

Affected Actions include:
- aws-actions/configure-aws-credentials (v2 currently in use)
- actions/upload-artifact (v3 currently in use)
- actions/download-artifact (v3 currently in use)
- actions/checkout (v3 currently in use)
- actions/cache (v3 currently in use)
- actions/setup-node (v3 currently in use)

This list of affected Actions has been compiled from warnings seen in CPMS. It is possible there are also others, so care should be taken to scope out _all_ affected Actions.

In particular, for the actions/download-artifact Action, additional care should be taken to ensure the actions/upload-artifact Action is updated at the same time. These Actions should both be updated to v4 at the same time, as cross-compatibility between versions is not supported: https://github.com/actions/download-artifact?tab=readme-ov-file#improvements

**Comment by JoshuaLicense** [comment]
Closed by: https://github.com/dvsa/.github/pull/56
